fertilizer:
  description:
    DisplayName: Fertilizer
    Category: Gardening
    Description: Grow huge trees and other plants with this highly efficient fertilizer.
    Usage: Use on a sapling or mushroom to enhance its growth. Make sure there is enough space for the plant.
