main: com.cavetale.trees.TreesPlugin
name: Trees

description: Custom Tree Seeds
author: StarTux

version: 0.1
api-version: '1.21.10'

depend: [Core, Mytems]
softdepend: []

commands:
  trees:
    description: Admin interface
    permission: trees.admin
    usage: /trees

permissions:
  trees.admin:
    description: use /trees
    default: op
